dist: trusty
language: node_js
node_js:
- '7'
before_install:
- export TZ='Asia/Shanghai'
- openssl aes-256-cbc -K $encrypted_e3c95c579d11_key -iv $encrypted_e3c95c579d11_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "xa0082249956"
- git config --global user.email "576810415@qq.com"
- git clone git@github.com:xa0082249956/xa0082249956.github.io.git .deploy_git
install:
- sudo apt install pandoc
- npm install hexo@beta -g
- npm install
script:
- touch db.json
- hexo clean
- hexo generate
- hexo deploy

branches:
  only:
  - master
